### ISSUE TITLE
Feature request - Versioning

### ISSUE THREAD

**Issue by MichalGrzegorzak** [yohsii/puck-cms-platform#6]
I think having a version history is a must for a CMS. Do you have a plan to add such feature? 
If not, could you share any tips for anyone who would dare to build it? :) Thanks!

**Comment by yohsii** [comment]
It does have a rollback feature where you can compare versions/revisions and rollback to previous revisions.
It's on the content tree settings for each content item

**Comment by yohsii** [comment]
The option is called `Revert`
