### ISSUE TITLE
Content Picker UI Delete Bug

### ISSUE THREAD

**Issue by paddlepaw** [yohsii/puck-cms-platform#7]
Hi,  I'm liking the CMS so far.  I found that the UI deletes items set with the content picker upon sort.  If you have a model with a content picker and you go into the backoffice to manage items you've chosen and you click to sort one it will delete the item if the mouse is over the icon with the up/down arrows when the click up event fires.  If i click down to sort an item and move the mouse slightly to the right of the icon it will not delete on click up.  I hope this makes sense.

**Comment by yohsii** [comment]
Browser please

**Comment by paddlepaw** [comment]
Firefox.

**Comment by yohsii** [comment]
ah, can confirm, firefox only issue but it's fixed now.

thanks for the feedback!

**Comment by paddlepaw** [comment]
That's what I get for using FF. Thanks for fixing it.
