### ISSUE TITLE
Wildcard domain mapping not properly restored

### ISSUE THREAD

**Issue by ghost** [yohsii/puck-cms-platform#8]
Steps to reproduce:

- Create 2 pages (first will be mapped to / )
- Remove first page
- Go to /
- You'll see `domain root not set, likely because there is no content.`

The only way to fix this is to delete all pages and then start over. Did I miss anything?
I noticed that `ApiController.DomainMapping()` calls `SetDomain` which could help but how can this be done?

**Comment by yohsii** [comment]
You should be able to go to the settings for the second page and set the domain mapping which is an option after clicking on the settings icon for the page

**Comment by yohsii** [comment]
Just set the domain mapping for the second page to asterisk for wildcard. The settings icon should be to the left of the page name in the content tree
