### ISSUE TITLE
Feature idea: flat file storage option

### ISSUE THREAD

**Issue by Jogai** [yohsii/puck-cms-platform#9]
Title says it all. For quickly spinning up a simple site a flat file cms is attractive I think.

**Comment by yohsii** [comment]
hi Jogai, there are no plans for flat file storage and it would be a big departure from the current architecture of Puck but if you want to start quickly you can in as simple as three steps.

in your appSettings.json:
1) set the connection string for SQLite to `Data Source=puck.db` 
2) then set `UseSQLServer` to `false` and `UseSQLite` to `true`.
3) set username and password

then you're all set to start the website from visual studio.

obviously using SQLite has it's limitations and performance implications but it can help your start quickly.

thanks for the suggestion
